theme: jekyll-theme-minimal

title:            Celestial Mead
description:      sic itur ad astra
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://celestialmead.github.io
