title:            Celestial Mead
description:      sic itur ad astra
show_excerpts:    false # set to true to show excerpts on the homepage
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://celestialmead.github.io

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Toronto
future:      false  # publish future dated posts --  true, false (default) 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# generate social links in footer
#twitter: jekyllrb
#github:  jekyll
rss: rss
# dribbble: jekyll
# facebook: jekyll
# flickr:   jekyll
# instagram: jekyll
# linkedin: jekyll
# pinterest: jekyll
# youtube: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram: jekyll
# googleplus: +jekyll
# microdotblog: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
